name: "My GitHub Action"
description: "An example GitHub Action"
author: "Jeremy Escobar"
inputs:
  input1:
    description: "An input for the action"
    required: true
outputs:
  output1:
    description: "An output from the action"
runs:
  steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Run Action"
      run: |
        echo "Hello, world!"
